### ISSUE TITLE
Resize attack is difficult to recover the watermark

### ISSUE THREAD

**Issue by luuil** [ChaoningZhang/Universal-Deep-Hiding#4]
First of all, thank the author for open source such a great method.

I tested a variety of attacks (**jpeg compression, occlusion, brightness, screenshots, etc.**), and the watermark recovery okay. However, it is difficult to recover the watermark due to **Resize** attacks alone.

My question is: 

Is the method itself not able to handle resize attacks well, or is it the way I run it incorrectly?

**Comment by ChaoningZhang** [comment]
Thanks for your interest in our work. I believe that our method should also handle resize attack well.
May I ask which pre-trained model are you testing on?
If you use our provided pretrained model, can you specify which one?
If you train it by yourself, can you tell me how you train it, especially what attacks you apply during the training stage?

**Comment by luuil** [comment]
Thanks for replying so quickly.
I used two pre-trained models: `training/main_udh` (UDH) and `training/main_watermarking` (WM). I found that both UDH and WM can't handle **resize** and **jpeg** well.

## UDH
 As shown below, the first row represents the **cover and the original watermark**, and the remaining represent the **Identity, Resize, and JPEG** attacks.

![image](https://user-images.githubusercontent.com/26055346/124586325-e2fbbf80-de88-11eb-990e-d980ca1c68c9.png)
![image](https://user-images.githubusercontent.com/26055346/124587262-02471c80-de8a-11eb-8503-621186ee3389.png)
![image](https://user-images.githubusercontent.com/26055346/124587301-0e32de80-de8a-11eb-8c96-32894e40bd87.png)

## WM
In addition, the images encoded with WM have obvious artifacts: **horizontal water-like stripes**.

As shown in the figure below, respectively represent **Identity,  Resize, and JPEG** attacks.

![image](https://user-images.githubusercontent.com/26055346/124587804-a29d4100-de8a-11eb-8d9a-9147ea8c9026.png)
![image](https://user-images.githubusercontent.com/26055346/124587946-cf515880-de8a-11eb-827d-8eb6ef32f2f7.png)
![image](https://user-images.githubusercontent.com/26055346/124588272-31aa5900-de8b-11eb-8cf1-23e933b32ae9.png)

**Comment by luuil** [comment]
> First of all, thank the author for open source such a great method.
> 
> I tested a variety of attacks (**jpeg compression, occlusion, brightness, screenshots, etc.**), and the watermark recovery okay. However, it is difficult to recover the watermark due to **Resize** attacks alone.
> 
> My question is:
> 
> Is the method itself not able to handle resize attacks well, or is it the way I run it incorrectly?

I verified again, and the result is that the model cann't handle both **resize and jpeg** attacks well, the image can refer to the previous reply.

**Comment by ChaoningZhang** [comment]
If I remember correctly, the model we provided as main_udh is used for the results in Table 1 and Figure 3. In other words, the model does not take any attack into account. Something seems to be wrong with the results you show with an identity regarding the revealed secret image. The revealed secret image in this context should be almost perfect, something as our figure 3 shows. I'm not sure what might be wrong here. I suggest you train the model by yourself again with our provided code. After training with a single GPU for around half an hour, you should already see an almost perfect revealed image. main_watermarking (WM) is trained with various types of attacks the performance is shown in Table 4. Table4 shows that indeed JPEG is a very challenging attack (higher value in Table 4 indicates worse performance). However, if you hide bits information instead of image, the performance would be reasonable, see Table 5. Admittedly, among all the attacks that we investigate, JPEG is the most difficult one. Regarding the resize attack, it would not work automatically unless we add the resize attack during the training stage. If you are interested, you can retrain the model with the resize attack added to the training stage. Please share your results here, if you give it a shot. I guess it should work fine. In summary, the key to making it robust is to add the relevant attack during the training stage. If the attack is non-differentiable or black-box please, please check our other work that will appear at ACM Multimedia 2021 with the code link at https://github.com/ChaoningZhang/Pseudo-Differentiable-JPEG. The artefacts on the container image or watermarked image would be a trade-off between the hiding and revealing quality. Adding adversarial training as Hidden: Hiding data with deep networks (ECCV2018) might also alleviate this problem. Overall, it is a trade-off issue. I hope I solved your issues. If you need more detailed help or discussion, you are also welcome to contact me through email, anytime ^_^

**Comment by luuil** [comment]
Thank you for your detailed reply.

It turns out that I ran **main_udh** incorrectly, that is, I should not use various attacks on it.

Because I want a version that can withstand attacks, I will spend time on **main_wm**. Next, I will consult you with some running and training details via email. I would like to thank you for helping in advance.

**Comment by ChaoningZhang** [comment]
Please feel free to contact me for a detailed discussion. I will close this issue here.
